apiVersion: skaffold/v1beta13
build:
  artifacts:
  - context: .
    docker:
      dockerfile: Dockerfile
    image: gcr.io/imperial-legacy-380605/tfx_churn_pipeline
  local:
    push: true
    useDockerCLI: true
  tagPolicy:
    envTemplate:
      template: latest
kind: Config
